version: '3'
services:
  app:
    container_name: mysqldbservice
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db          
    networks:
      - stack

  db:
    image: mysql:5.7
    container_name: full_db_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: comp440
      MYSQL_USER: comp
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    networks:
      - stack

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - stack
    restart: unless-stopped


volumes:
  api:
  db_data:            

networks:
  stack:
    driver: bridge